### PR TITLE
Function tweak

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
- Just wanted to note that this is a breaking change for the function, but will make it consistent with all other functions in the package.

**Comment by jeremiahpslewis** [comment]
Also, want to enable automatic test builds on pull requests?
https://blog.travis-ci.com/2012-09-04-pull-requests-just-got-even-more-awesome/

**Comment by Ironholds** [comment]
It will make it consistent by advertising to users functionality that does not exist. That's really not consistency.

There is no way to get non-daily article pageviews right now, so why would we claim otherwise?

**Comment by jeremiahpslewis** [comment]
There's a warning built in to inform users that the functionality is not available. It also makes it clear to users exactly what granularity they are getting. Given that there is a default parameter, I don't expect this should lead to too much confusion.

**Comment by Ironholds** [comment]
The warning is just that; a warning. It works out the thing doesn't work, and then runs it anyway. And then produces an error, and _then_ notifies the user.

**Comment by Ironholds** [comment]
Similarly, there's a reformat argument that does absolutely nothing because there's no reformat method for top_articles. Meanwhile there's documentation added that claims it does.

**Comment by jeremiahpslewis** [comment]
Hmm...reformat is necessary to take the object from json-like (a list of lists) to data.frame. This works for `top_articles` just as for all other functions. But as a result of the refactoring, reformatting takes place within pv_query.

**Comment by Ironholds** [comment]
Ahh, gotcha; misread.

I'm deeply uncomfortable with implying to users there is functionality that doesn't exist. I'd like the additional granularity args removed before I merge, please.

**Comment by jeremiahpslewis** [comment]
This is now covered by the other pull request.

**Pull request closed without merging**
